import AffineTverberg.CoefficientSmallChains
import AffineTverberg.SmallSingular

set_option linter.style.header false

/-!
# Subdivision makes singular chains small over arbitrary fields

The actual singular chain groups over an arbitrary field are generated by
singular simplices. A Lebesgue number and the real mesh estimate make every
chain small after a finite number of subdivisions. No change is made to the
geometric simplex or the topology of the space.
-/

noncomputable section

open CategoryTheory Limits Simplicial Metric AffineTverberg.AffChain
open scoped BigOperators

namespace AffineTverberg.Coefficients.AffChain

variable (𝕜 : Type) [Field 𝕜]
variable {X : TopCat.{0}}

/-- The basis element of the singular chain group given by a singular simplex. -/
def sElt {n : ℕ} (σ : C(Δt n, X)) : (singChains 𝕜 X).X n := (ιs 𝕜 (singSimplex σ)).hom (1 : 𝕜)

lemma realChain_sElt {k n : ℕ} (σ : C(Δt k, X)) (w : Fin (n + 1) → Δt k) :
    ((realChain 𝕜 σ).f n).hom (elt 𝕜 w) = sElt 𝕜 (σ.comp (affMap w)) := by
  have h := congrArg (fun (g : ModuleCat.of 𝕜 𝕜 ⟶ (singChains 𝕜 X).X n) => g.hom (1 : 𝕜))
    (ιa_realChain_singSimplex 𝕜 σ w)
  simpa only [ModuleCat.hom_comp, LinearMap.comp_apply, elt, sElt] using h

lemma sElt_d {n : ℕ} (σ : C(Δt (n + 1), X)) :
    ((singChains 𝕜 X).d (n + 1) n).hom (sElt 𝕜 σ) =
      ∑ i : Fin (n + 2), (-1 : 𝕜) ^ (i : ℕ) • sElt 𝕜 (σ.comp (faceMap i)) := by
  have h := (TopCat.toSSet.obj X).ιChainComplex_d (ModuleCat.of 𝕜 𝕜) (singSimplex σ)
  have h2 := congrArg (fun (g : ModuleCat.of 𝕜 𝕜 ⟶ (singChains 𝕜 X).X n) => g.hom (1 : 𝕜)) h
  simp only [ModuleCat.hom_comp, LinearMap.comp_apply] at h2
  change ((singChains 𝕜 X).d (n + 1) n).hom ((ιs 𝕜 (singSimplex σ)).hom (1 : 𝕜)) = _
  rw [h2]
  rw [show ((∑ i : Fin (n + 2), (-1 : ℤ) ^ (i : ℕ) •
        ιs 𝕜 ((TopCat.toSSet.obj X).δ i (singSimplex σ))).hom (1 : 𝕜)) =
      ∑ i : Fin (n + 2), ((-1 : ℤ) ^ (i : ℕ)) •
        ((ιs 𝕜 ((TopCat.toSSet.obj X).δ i (singSimplex σ))).hom (1 : 𝕜)) by simp]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [← Int.cast_smul_eq_zsmul 𝕜 ((-1 : ℤ) ^ (i : ℕ))]
  push_cast
  rw [delta_singSimplex]
  rfl

/-! ### Subdivision commutes with realization -/

/-- The subdivision of the realization of an affine chain along `σ` is the
realization of its affine subdivision. -/
theorem realChain_sdSing {k n : ℕ} (σ : C(Δt k, X)) :
    (realChain 𝕜 σ).f n ≫ sdSing 𝕜 X n = sdHom 𝕜 k n ≫ (realChain 𝕜 σ).f n := by
  refine affChains_hom_ext 𝕜 fun v => ?_
  have htuple : (fun a => affPoint v (idTuple n a)) = v := funext fun a => affPoint_vertex v a
  have hmid : ιa 𝕜 (idTuple n) ≫ sdHom 𝕜 n n ≫ (pushChain 𝕜 v).f n = ιa 𝕜 v ≫ sdHom 𝕜 k n := by
    rw [pushChain_sdHom 𝕜, ← Category.assoc, ιa_pushChain 𝕜, htuple]
  calc ιa 𝕜 v ≫ (realChain 𝕜 σ).f n ≫ sdSing 𝕜 X n
      = ιs 𝕜 (singSimplex (σ.comp (affMap v))) ≫ sdSing 𝕜 X n := by
        rw [← Category.assoc, ιa_realChain_singSimplex 𝕜]
    _ = ιa 𝕜 (idTuple n) ≫ sdHom 𝕜 n n ≫ (realChain 𝕜 (σ.comp (affMap v))).f n := ιs_sdSing 𝕜 _
    _ = ιa 𝕜 (idTuple n) ≫ sdHom 𝕜 n n ≫ ((pushChain 𝕜 v).f n ≫ (realChain 𝕜 σ).f n) := by
        rw [realChain_comp_affMap 𝕜]
    _ = (ιa 𝕜 (idTuple n) ≫ sdHom 𝕜 n n ≫ (pushChain 𝕜 v).f n) ≫ (realChain 𝕜 σ).f n := by
        simp only [Category.assoc]
    _ = (ιa 𝕜 v ≫ sdHom 𝕜 k n) ≫ (realChain 𝕜 σ).f n := by rw [hmid]
    _ = ιa 𝕜 v ≫ sdHom 𝕜 k n ≫ (realChain 𝕜 σ).f n := by rw [Category.assoc]

/-- The iterated subdivision of the realization of an affine chain along `σ` is
the realization of its iterated affine subdivision. -/
theorem realChain_sdIterMap {k n : ℕ} (σ : C(Δt k, X)) (m : ℕ) :
    (realChain 𝕜 σ).f n ≫ (sdIterMap 𝕜 X m).f n = sdIterHom 𝕜 k m n ≫ (realChain 𝕜 σ).f n := by
  induction m with
  | zero => simp
  | succ m ih =>
    rw [sdIterMap_succ 𝕜]
    change (realChain 𝕜 σ).f n ≫ ((sdIterMap 𝕜 X m).f n ≫ (sdChainMap 𝕜 X).f n) = _
    rw [← Category.assoc, ih, Category.assoc]
    change sdIterHom 𝕜 k m n ≫ ((realChain 𝕜 σ).f n ≫ sdSing 𝕜 X n) = _
    rw [realChain_sdSing 𝕜, sdIterHom_succ 𝕜, Category.assoc]

lemma sElt_eq_realChain_elt {n : ℕ} (σ : C(Δt n, X)) :
    sElt 𝕜 σ = ((realChain 𝕜 σ).f n).hom (elt 𝕜 (idTuple n)) := by
  rw [realChain_sElt 𝕜]
  congr 1
  rw [affMap_idTuple]
  rfl

lemma sdIterMap_sElt {n : ℕ} (σ : C(Δt n, X)) (m : ℕ) :
    ((sdIterMap 𝕜 X m).f n).hom (sElt 𝕜 σ) =
      ((realChain 𝕜 σ).f n).hom ((sdIterHom 𝕜 n m n).hom (elt 𝕜 (idTuple n))) := by
  rw [sElt_eq_realChain_elt 𝕜]
  have h := congrArg (fun (g : (affChains 𝕜 n).X n ⟶ (singChains 𝕜 X).X n) =>
    g.hom (elt 𝕜 (idTuple n))) (realChain_sdIterMap 𝕜 σ m)
  simpa only [ModuleCat.hom_comp, LinearMap.comp_apply] using h

/-! ### Small chains -/

variable {ι : Type}

/-- The set of basis singular `n`-chains whose image lies inside a single
member of the family `U`. -/
def smallSet (U : ι → Set X) (n : ℕ) : Set ((singChains 𝕜 X).X n) :=
  {x | ∃ (σ : C(Δt n, X)) (i : ι), (∀ t, σ t ∈ U i) ∧ x = sElt 𝕜 σ}

/-- The submodule of `U`-small singular `n`-chains. -/
def smallChains (U : ι → Set X) (n : ℕ) : Submodule 𝕜 ((singChains 𝕜 X).X n) :=
  Submodule.span 𝕜 (smallSet 𝕜 U n)

lemma sElt_mem_smallChains {U : ι → Set X} {n : ℕ} {σ : C(Δt n, X)} {i : ι}
    (h : ∀ t, σ t ∈ U i) : sElt 𝕜 σ ∈ smallChains 𝕜 U n :=
  Submodule.subset_span ⟨σ, i, h, rfl⟩

/-- The submodule of singular `n`-chains carried by a single subset `S` of
`X`. -/
def chainsIn (S : Set X) (n : ℕ) : Submodule 𝕜 ((singChains 𝕜 X).X n) :=
  Submodule.span 𝕜 {x | ∃ σ : C(Δt n, X), (∀ t, σ t ∈ S) ∧ x = sElt 𝕜 σ}

lemma sElt_mem_chainsIn {S : Set X} {n : ℕ} {σ : C(Δt n, X)} (h : ∀ t, σ t ∈ S) :
    sElt 𝕜 σ ∈ chainsIn 𝕜 S n :=
  Submodule.subset_span ⟨σ, h, rfl⟩

/-- The small chains of a family are exactly the sum of the chains carried by
its members. This is the description of the small chains used in the
Mayer-Vietoris argument. -/
theorem smallChains_eq_iSup (U : ι → Set X) (n : ℕ) :
    smallChains 𝕜 U n = ⨆ i, chainsIn 𝕜 (U i) n := by
  refine le_antisymm (Submodule.span_le.2 ?_) (iSup_le fun i => Submodule.span_le.2 ?_)
  · rintro x ⟨σ, i, hσ, rfl⟩
    exact le_iSup (fun i => chainsIn 𝕜 (U i) n) i (sElt_mem_chainsIn 𝕜 hσ)
  · rintro x ⟨σ, hσ, rfl⟩
    exact sElt_mem_smallChains 𝕜 (i := i) hσ

/-- **The small chains form a subcomplex**: the boundary of a `U`-small chain
is `U`-small. -/
theorem smallChains_d (U : ι → Set X) (n : ℕ) {x : (singChains 𝕜 X).X (n + 1)}
    (hx : x ∈ smallChains 𝕜 U (n + 1)) :
    ((singChains 𝕜 X).d (n + 1) n).hom x ∈ smallChains 𝕜 U n := by
  have hle : smallChains 𝕜 U (n + 1) ≤
      (smallChains 𝕜 U n).comap ((singChains 𝕜 X).d (n + 1) n).hom := by
    refine Submodule.span_le.2 ?_
    rintro y ⟨σ, i, hσ, rfl⟩
    change ((singChains 𝕜 X).d (n + 1) n).hom (sElt 𝕜 σ) ∈ smallChains 𝕜 U n
    rw [sElt_d 𝕜]
    refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
    exact sElt_mem_smallChains 𝕜 (i := i) fun t => hσ _
  exact hle hx


/-- **The small chain reduction for a single singular simplex.** Given an open
cover `U` of `X` and a singular simplex `σ`, some iterate of the barycentric
subdivision carries `σ` into the submodule of `U`-small chains. -/
theorem exists_sdIterMap_sElt_mem_smallChains {ι : Type} (U : ι → Set X)
    (hU : ∀ i, IsOpen (U i)) (hcov : ∀ x : X, ∃ i, x ∈ U i) {n : ℕ} (σ : C(Δt n, X)) :
    ∃ m : ℕ, ((sdIterMap 𝕜 X m).f n).hom (sElt 𝕜 σ) ∈ smallChains 𝕜 U n := by
  classical
  -- the pullback cover of the standard simplex
  have hopen : ∀ i, IsOpen (σ ⁻¹' U i) := fun i => (hU i).preimage σ.continuous
  have hcover : (Set.univ : Set (Δt n)) ⊆ ⋃ i, σ ⁻¹' U i := by
    intro t _
    obtain ⟨i, hi⟩ := hcov (σ t)
    exact Set.mem_iUnion.2 ⟨i, hi⟩
  obtain ⟨δ, hδ0, hδ⟩ :=
    lebesgue_number_lemma_of_metric (s := (Set.univ : Set (Δt n)))
      (isCompact_univ) hopen hcover
  -- choose an iterate whose mesh is smaller than the Lebesgue number
  have hr : (n : ℝ) / ((n : ℝ) + 1) < 1 := by
    rw [div_lt_one (by positivity)]
    linarith
  obtain ⟨m, hm⟩ := exists_pow_lt_of_lt_one hδ0 hr
  refine ⟨m, ?_⟩
  rw [sdIterMap_sElt 𝕜]
  have hmesh := sdIterHom_elt_mem_spanTuples 𝕜 (k := n) (n := n) m (idTuple n) 1 zero_le_one
    (fun a b => dist_le_one _ _)
  refine map_mem_of_mem_spanTuples 𝕜 ((realChain 𝕜 σ).f n) ?_ hmesh
  rintro w ⟨-, hw⟩
  rw [realChain_sElt 𝕜]
  obtain ⟨i, hi⟩ := hδ (w 0) (Set.mem_univ _)
  refine sElt_mem_smallChains 𝕜 (i := i) fun t => ?_
  have hball : affPoint w t ∈ ball (w 0) δ :=
    affMap_mem_ball w (((n : ℝ) / ((n : ℝ) + 1)) ^ m * 1) δ (by simpa using hw)
      (by simpa using hm) t
  exact hi hball

/-- The basis elements span the singular chain groups. -/
lemma singChains_span_sElt (n : ℕ) :
    Submodule.span 𝕜 (Set.range (fun σ : C(Δt n, X) => sElt 𝕜 σ)) = ⊤ := by
  set S := Submodule.span 𝕜 (Set.range (fun σ : C(Δt n, X) => sElt 𝕜 σ)) with hS
  have hmem : ∀ (σ : C(Δt n, X)) (r : 𝕜), (ιs 𝕜 (singSimplex σ)).hom r ∈ S := by
    intro σ r
    have hr : (ιs 𝕜 (singSimplex σ)).hom r = r • sElt 𝕜 σ := by
      rw [sElt, ← map_smul]
      congr 1
      simp
    rw [hr]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_range_self σ))
  have hq : (ModuleCat.ofHom S.mkQ :
      (singChains 𝕜 X).X n ⟶ ModuleCat.of 𝕜 (((singChains 𝕜 X).X n) ⧸ S)) = 0 := by
    refine singChains_hom_ext' 𝕜 fun σ => ?_
    refine ModuleCat.hom_ext (LinearMap.ext fun r => ?_)
    change S.mkQ ((ιs 𝕜 (singSimplex σ)).hom r) = (0 : ((singChains 𝕜 X).X n) ⧸ S)
    exact (Submodule.Quotient.mk_eq_zero _).2 (hmem σ r)
  refine eq_top_iff.2 fun x _ => ?_
  have hx := congrArg (fun (g : (singChains 𝕜 X).X n ⟶
    ModuleCat.of 𝕜 (((singChains 𝕜 X).X n) ⧸ S)) => g.hom x) hq
  exact (Submodule.Quotient.mk_eq_zero _).1 hx

/-- **The small chain reduction.** Given an open cover `U` of `X`, every
singular chain becomes `U`-small after finitely many barycentric
subdivisions. -/
theorem exists_sdIterMap_mem_smallChains {ι : Type} (U : ι → Set X)
    (hU : ∀ i, IsOpen (U i)) (hcov : ∀ x : X, ∃ i, x ∈ U i) {n : ℕ}
    (x : (singChains 𝕜 X).X n) :
    ∃ m : ℕ, ((sdIterMap 𝕜 X m).f n).hom x ∈ smallChains 𝕜 U n := by
  classical
  -- the set of chains for which some iterate works is a submodule
  have hmono : ∀ (m m' : ℕ), m ≤ m' → ∀ y : (singChains 𝕜 X).X n,
      ((sdIterMap 𝕜 X m).f n).hom y ∈ smallChains 𝕜 U n →
      ((sdIterMap 𝕜 X m').f n).hom y ∈ smallChains 𝕜 U n := by
    intro m m' hmm
    obtain ⟨p, rfl⟩ := Nat.exists_eq_add_of_le hmm
    induction p with
    | zero => intro y hy; simpa using hy
    | succ p ih =>
      intro y hy
      have hstep : ∀ z : (singChains 𝕜 X).X n, z ∈ smallChains 𝕜 U n →
          ((sdChainMap 𝕜 X).f n).hom z ∈ smallChains 𝕜 U n := by
        intro z hz
        have hle : smallChains 𝕜 U n ≤ (smallChains 𝕜 U n).comap ((sdChainMap 𝕜 X).f n).hom := by
          refine Submodule.span_le.2 ?_
          rintro y' ⟨τ, i, hτ, rfl⟩
          change ((sdChainMap 𝕜 X).f n).hom (sElt 𝕜 τ) ∈ smallChains 𝕜 U n
          have hτ' : ((sdChainMap 𝕜 X).f n).hom (sElt 𝕜 τ) =
              ((realChain 𝕜 τ).f n).hom ((sdHom 𝕜 n n).hom (elt 𝕜 (idTuple n))) := by
            change (sdSing 𝕜 X n).hom (sElt 𝕜 τ) = _
            rw [sElt_eq_realChain_elt 𝕜]
            have h := congrArg (fun (g : (affChains 𝕜 n).X n ⟶ (singChains 𝕜 X).X n) =>
              g.hom (elt 𝕜 (idTuple n))) (realChain_sdSing 𝕜 (n := n) τ)
            simpa only [ModuleCat.hom_comp, LinearMap.comp_apply] using h
          rw [hτ']
          have hmesh := sdHom_elt_mem_spanTuples 𝕜 (k := n) n (idTuple n) 1 zero_le_one
            (fun a b => dist_le_one _ _)
          refine map_mem_of_mem_spanTuples 𝕜 ((realChain 𝕜 τ).f n) ?_ hmesh
          rintro w ⟨-, -⟩
          rw [realChain_sElt 𝕜]
          exact sElt_mem_smallChains 𝕜 (i := i) fun t => hτ _
        exact hle hz
      have := ih (by omega) y hy
      have hsucc : ((sdIterMap 𝕜 X (m + (p + 1))).f n).hom y =
          ((sdChainMap 𝕜 X).f n).hom (((sdIterMap 𝕜 X (m + p)).f n).hom y) := by
        rw [show m + (p + 1) = (m + p) + 1 from rfl, sdIterMap_succ 𝕜]
        rfl
      rw [hsucc]
      exact hstep _ this
  -- it suffices to treat basis elements
  have hx : x ∈ Submodule.span 𝕜 (Set.range (fun σ : C(Δt n, X) => sElt 𝕜 σ)) := by
    rw [singChains_span_sElt 𝕜]; trivial
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨σ, rfl⟩ := hy
    exact exists_sdIterMap_sElt_mem_smallChains 𝕜 U hU hcov σ
  | zero => exact ⟨0, by simp⟩
  | add a b _ _ ha hb =>
    obtain ⟨ma, hma⟩ := ha
    obtain ⟨mb, hmb⟩ := hb
    refine ⟨max ma mb, ?_⟩
    rw [map_add]
    exact Submodule.add_mem _ (hmono _ _ (le_max_left _ _) _ hma)
      (hmono _ _ (le_max_right _ _) _ hmb)
  | smul c a _ ha =>
    obtain ⟨m, hm⟩ := ha
    exact ⟨m, by rw [map_smul]; exact Submodule.smul_mem _ _ hm⟩

end AffineTverberg.Coefficients.AffChain

