import Mathlib.Analysis.LocallyConvex.Separation
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.LinearAlgebra.LinearIndependent.Defs

set_option linter.style.header false

/-!
# A finite Farkas lemma

This file provides the elementary polyhedral input needed by
`AffineTverberg/PolyhedralTop.lean`: the cone generated by finitely many
vectors of a normed space is closed, and consequently a finite system of
inhomogeneous linear inequalities

`a (d i) ≥ h i`  (`i` ranging over a finite index set)

is solvable by a continuous linear functional `a` as soon as it is not
contradicted by a nonnegative combination of its own constraints.

The closedness proof is the standard conic Carathéodory induction: if the
generators are linearly independent, the cone is the image of the closed
orthant under a closed embedding; otherwise a nontrivial linear relation
lets one drop a generator, and the cone is a finite union of cones with
fewer generators.
-/

noncomputable section

open Set

namespace AffineTverberg

variable {ι V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- The convex cone generated by the finite family `v` indexed by `s`. -/
def finiteCone (s : Finset ι) (v : ι → V) : Set V :=
  {x | ∃ l : ι → ℝ, (∀ i ∈ s, 0 ≤ l i) ∧ x = ∑ i ∈ s, l i • v i}

theorem zero_mem_finiteCone (s : Finset ι) (v : ι → V) : (0 : V) ∈ finiteCone s v :=
  ⟨0, fun _ _ ↦ le_refl 0, by simp⟩

theorem generator_mem_finiteCone {s : Finset ι} {v : ι → V} {i : ι}
    (hi : i ∈ s) : v i ∈ finiteCone s v := by
  classical
  refine ⟨fun j ↦ if j = i then 1 else 0, fun j _ ↦ by positivity, ?_⟩
  rw [Finset.sum_eq_single i]
  · simp
  · intro j _ hj; simp [hj]
  · intro h; exact absurd hi h

theorem smul_mem_finiteCone {s : Finset ι} {v : ι → V} {x : V} (hx : x ∈ finiteCone s v)
    {t : ℝ} (ht : 0 ≤ t) : t • x ∈ finiteCone s v := by
  obtain ⟨l, hl, rfl⟩ := hx
  refine ⟨fun i ↦ t * l i, fun i hi ↦ mul_nonneg ht (hl i hi), ?_⟩
  rw [Finset.smul_sum]
  exact Finset.sum_congr rfl fun i _ ↦ by rw [smul_smul]

theorem convex_finiteCone (s : Finset ι) (v : ι → V) : Convex ℝ (finiteCone s v) := by
  rintro x ⟨l, hl, rfl⟩ y ⟨m, hm, rfl⟩ a b ha hb _
  refine ⟨fun i ↦ a * l i + b * m i, fun i hi ↦ by
      have := mul_nonneg ha (hl i hi); have := mul_nonneg hb (hm i hi); linarith, ?_⟩
  rw [Finset.smul_sum, Finset.smul_sum, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [smul_smul, smul_smul, add_smul]

theorem finiteCone_mono {s t : Finset ι} (hst : s ⊆ t) (v : ι → V) :
    finiteCone s v ⊆ finiteCone t v := by
  classical
  rintro x ⟨l, hl, rfl⟩
  refine ⟨fun i ↦ if i ∈ s then l i else 0, fun i _ ↦ ?_, ?_⟩
  · by_cases hi : i ∈ s
    · simpa [hi] using hl i hi
    · simp [hi]
  rw [← Finset.sum_subset hst]
  · exact Finset.sum_congr rfl fun i hi ↦ by simp [hi]
  · intro i _ hi; simp [hi]

/-- The cone generated by a linearly independent finite family is closed:
it is the image of the closed orthant under a closed embedding. -/
theorem isClosed_finiteCone_of_linearIndependent (s : Finset ι) (v : ι → V)
    (hli : LinearIndependent ℝ fun i : (s : Set ι) ↦ v i) :
    IsClosed (finiteCone s v) := by
  classical
  set w : ↥(s : Set ι) → V := fun i ↦ v i with hw
  set φ : (↥(s : Set ι) → ℝ) →ₗ[ℝ] V := Fintype.linearCombination ℝ w with hφ
  have hφapply : ∀ f, φ f = ∑ i : ↥(s : Set ι), f i • w i := fun f ↦ rfl
  have hker : LinearMap.ker φ = ⊥ := by
    rw [LinearMap.ker_eq_bot']
    intro f hf
    funext i
    exact Fintype.linearIndependent_iff.1 hli f (by rw [← hφapply]; exact hf) i
  have hemb : Topology.IsClosedEmbedding φ := LinearMap.isClosedEmbedding_of_injective hker
  have horthant : IsClosed {f : ↥(s : Set ι) → ℝ | ∀ i, 0 ≤ f i} := by
    have : {f : ↥(s : Set ι) → ℝ | ∀ i, 0 ≤ f i} = ⋂ i, {f : ↥(s : Set ι) → ℝ | 0 ≤ f i} := by
      ext f; simp
    rw [this]
    exact isClosed_iInter fun i ↦
      isClosed_le continuous_const (continuous_apply i)
  have himage : finiteCone s v = φ '' {f : ↥(s : Set ι) → ℝ | ∀ i, 0 ≤ f i} := by
    ext x
    constructor
    · rintro ⟨l, hl, rfl⟩
      refine ⟨fun i ↦ l i, fun i ↦ hl i i.2, ?_⟩
      rw [hφapply]
      exact Finset.sum_coe_sort s (fun i ↦ l i • v i)
    · rintro ⟨f, hf, rfl⟩
      refine ⟨fun i ↦ if h : i ∈ s then f ⟨i, h⟩ else 0, fun i hi ↦ ?_, ?_⟩
      · simp only [hi, ↓reduceDIte]
        exact hf _
      rw [hφapply, ← Finset.sum_coe_sort s (fun i ↦ (if h : i ∈ s then f ⟨i, h⟩ else 0) • v i)]
      exact Finset.sum_congr rfl fun i _ ↦ by simp [hw]
  rw [himage]
  exact hemb.isClosedMap _ horthant

/-- The conic Carathéodory step: if the generators satisfy a nontrivial
linear relation, the cone is the union of the cones on proper subfamilies. -/
theorem finiteCone_eq_biUnion_erase_of_relation [DecidableEq ι] {s : Finset ι} {v : ι → V}
    {mu : ι → ℝ} (hrel : ∑ i ∈ s, mu i • v i = 0) {i₁ : ι} (hi₁ : i₁ ∈ s) (hpos : 0 < mu i₁) :
    finiteCone s v = ⋃ i ∈ (s : Set ι), finiteCone (s.erase i) v := by
  apply Subset.antisymm
  · rintro x ⟨l, hl, rfl⟩
    set P : Finset ι := s.filter fun i ↦ 0 < mu i with hP
    have hPne : P.Nonempty := ⟨i₁, by simp [hP, hi₁, hpos]⟩
    obtain ⟨i₀, hi₀P, hmin⟩ := P.exists_min_image (fun i ↦ l i / mu i) hPne
    have hi₀s : i₀ ∈ s := (Finset.mem_filter.1 hi₀P).1
    have hi₀pos : 0 < mu i₀ := (Finset.mem_filter.1 hi₀P).2
    set t : ℝ := l i₀ / mu i₀ with ht
    have ht0 : 0 ≤ t := div_nonneg (hl i₀ hi₀s) hi₀pos.le
    set l' : ι → ℝ := fun i ↦ l i - t * mu i with hl'
    have hl'nonneg : ∀ i ∈ s, 0 ≤ l' i := by
      intro i hi
      by_cases hmui : 0 < mu i
      · have hiP : i ∈ P := by simp [hP, hi, hmui]
        have := hmin i hiP
        have : t * mu i ≤ l i := by
          rw [ht]
          calc l i₀ / mu i₀ * mu i ≤ (l i / mu i) * mu i := by
                exact mul_le_mul_of_nonneg_right this hmui.le
            _ = l i := by field_simp
        simpa [hl'] using this
      · have hmui' : mu i ≤ 0 := le_of_not_gt hmui
        have : t * mu i ≤ 0 := mul_nonpos_of_nonneg_of_nonpos ht0 hmui'
        have := hl i hi
        simp only [hl']
        linarith
    have hl'zero : l' i₀ = 0 := by
      simp only [hl', ht]
      field_simp
      ring
    have hsum : ∑ i ∈ s, l' i • v i = ∑ i ∈ s, l i • v i := by
      have : ∑ i ∈ s, l' i • v i
          = ∑ i ∈ s, l i • v i - t • ∑ i ∈ s, mu i • v i := by
        rw [Finset.smul_sum, ← Finset.sum_sub_distrib]
        exact Finset.sum_congr rfl fun i _ ↦ by
          simp only [hl', smul_smul, sub_smul]
      rw [this, hrel, smul_zero, sub_zero]
    refine mem_biUnion (by exact_mod_cast hi₀s)
      ⟨l', fun i hi ↦ hl'nonneg i (Finset.mem_of_mem_erase hi), ?_⟩
    have hsplit : ∑ i ∈ s, l' i • v i = l' i₀ • v i₀ + ∑ i ∈ s.erase i₀, l' i • v i :=
      (Finset.add_sum_erase s (fun i ↦ l' i • v i) hi₀s).symm
    rw [← hsum, hsplit, hl'zero, zero_smul, zero_add]
  · refine iUnion₂_subset fun i _ ↦ finiteCone_mono (Finset.erase_subset i s) v

/-- **The cone generated by a finite family of vectors is closed.** -/
theorem isClosed_finiteCone (s : Finset ι) (v : ι → V) : IsClosed (finiteCone s v) := by
  classical
  suffices H : ∀ n : ℕ, ∀ s : Finset ι, s.card = n → IsClosed (finiteCone s v) from
    H s.card s rfl
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro s hcard
    by_cases hli : LinearIndependent ℝ fun i : (s : Set ι) ↦ v i
    · exact isClosed_finiteCone_of_linearIndependent s v hli
    · obtain ⟨g, hg0, i₁, hi₁⟩ := Fintype.not_linearIndependent_iff.1 hli
      set mu : ι → ℝ := fun i ↦ if h : i ∈ s then g ⟨i, h⟩ else 0 with hmu
      have hmusum : ∑ i ∈ s, mu i • v i = 0 := by
        rw [← Finset.sum_coe_sort s (fun i ↦ mu i • v i), ← hg0]
        exact Finset.sum_congr rfl fun i _ ↦ by simp [hmu, i.2]
      have hmune : mu i₁ ≠ 0 := by simpa [hmu, i₁.2] using hi₁
      have hi₁s : (i₁ : ι) ∈ s := i₁.2
      have hdecomp : ∃ (nu : ι → ℝ) (i : ι), i ∈ s ∧ 0 < nu i ∧ ∑ j ∈ s, nu j • v j = 0 := by
        rcases lt_or_gt_of_ne hmune with hneg | hpos
        · refine ⟨fun j ↦ -mu j, i₁, hi₁s, by simpa using hneg, ?_⟩
          rw [show ∑ j ∈ s, (-mu j) • v j = -∑ j ∈ s, mu j • v j by
            rw [← Finset.sum_neg_distrib]
            exact Finset.sum_congr rfl fun j _ ↦ by rw [neg_smul], hmusum, neg_zero]
        · exact ⟨mu, i₁, hi₁s, hpos, hmusum⟩
      obtain ⟨nu, i₀, hi₀s, hi₀pos, hnusum⟩ := hdecomp
      rw [finiteCone_eq_biUnion_erase_of_relation hnusum hi₀s hi₀pos]
      refine s.finite_toSet.isClosed_biUnion fun i hi ↦ ?_
      have hi' : i ∈ s := hi
      refine ih (s.erase i).card ?_ (s.erase i) rfl
      rw [← hcard]
      exact Finset.card_erase_lt_of_mem hi'

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

/-- **Finite Farkas lemma.**  A finite system of linear inequalities
`h i ≤ a (d i)` has a solution among the continuous linear functionals as
soon as no nonnegative combination of the constraint vectors vanishes while
the corresponding combination of the right-hand sides is positive. -/
theorem exists_continuousLinearMap_ge_of_forall_nonneg_combination
    (s : Finset ι) (d : ι → F) (h : ι → ℝ)
    (hyp : ∀ l : ι → ℝ, (∀ i ∈ s, 0 ≤ l i) → ∑ i ∈ s, l i • d i = 0 →
      ∑ i ∈ s, l i * h i ≤ 0) :
    ∃ a : F →L[ℝ] ℝ, ∀ i ∈ s, h i ≤ a (d i) := by
  classical
  set u : ι → F × ℝ := fun i ↦ (d i, h i) with hu
  set C : Set (F × ℝ) := finiteCone s u with hC
  have hCclosed : IsClosed C := isClosed_finiteCone s u
  have hCconvex : Convex ℝ C := convex_finiteCone s u
  have hsum_fst : ∀ l : ι → ℝ, (∑ i ∈ s, l i • u i).1 = ∑ i ∈ s, l i • d i := by
    intro l; rw [Prod.fst_sum]; rfl
  have hsum_snd : ∀ l : ι → ℝ, (∑ i ∈ s, l i • u i).2 = ∑ i ∈ s, l i * h i := by
    intro l; rw [Prod.snd_sum]; rfl
  have hnot : ((0 : F), (1 : ℝ)) ∉ C := by
    rintro ⟨l, hl, heq⟩
    have h1 : ∑ i ∈ s, l i • d i = 0 := by
      have := congrArg Prod.fst heq
      rw [hsum_fst] at this
      exact this.symm
    have h2 : ∑ i ∈ s, l i * h i = 1 := by
      have := congrArg Prod.snd heq
      rw [hsum_snd] at this
      exact this.symm
    have := hyp l hl h1
    rw [h2] at this
    linarith
  obtain ⟨Λ, c, hΛlt, hΛC⟩ := geometric_hahn_banach_point_closed hCconvex hCclosed hnot
  have hzero : Λ 0 = 0 := map_zero Λ
  have hc : c < 0 := by
    have := hΛC 0 (zero_mem_finiteCone s u)
    rw [hzero] at this
    exact this
  have hΛnonneg : ∀ x ∈ C, 0 ≤ Λ x := by
    intro x hx
    by_contra hlt
    rw [not_le] at hlt
    have hpos : 0 < c / Λ x := div_pos_of_neg_of_neg hc hlt
    have hmem : (c / Λ x) • x ∈ C := smul_mem_finiteCone hx hpos.le
    have := hΛC _ hmem
    rw [map_smul] at this
    simp only [smul_eq_mul] at this
    rw [div_mul_cancel₀ _ (ne_of_lt hlt)] at this
    exact absurd this (lt_irrefl c)
  set beta : ℝ := Λ (0, 1) with hbeta
  have hbetaneg : beta < 0 := hΛlt.trans hc
  set A : F →L[ℝ] ℝ := Λ.comp (ContinuousLinearMap.inl ℝ F ℝ) with hA
  have hΛsplit : ∀ (x : F) (t : ℝ), Λ (x, t) = A x + t * beta := by
    intro x t
    have : ((x, t) : F × ℝ) = (x, 0) + t • ((0 : F), (1 : ℝ)) := by
      simp
    rw [this, map_add, map_smul]
    simp [hA, hbeta]
  refine ⟨(-beta)⁻¹ • A, fun i hi ↦ ?_⟩
  have hui : u i ∈ C := generator_mem_finiteCone hi
  have h0 : 0 ≤ Λ (u i) := hΛnonneg _ hui
  rw [show u i = (d i, h i) from rfl, hΛsplit] at h0
  have hpos : 0 < -beta := by linarith
  have : h i * (-beta) ≤ A (d i) := by nlinarith
  have := (le_div_iff₀ hpos).2 this
  simpa [smul_apply, smul_eq_mul, div_eq_inv_mul] using this

end AffineTverberg
