import Mathlib.Analysis.Convex.Exposed
import Mathlib.Analysis.Convex.SimplicialComplex.Basic
import Mathlib.LinearAlgebra.AffineSpace.AffineMap
import Mathlib.Topology.Homeomorph.Defs
import Mathlib.Topology.MetricSpace.Pseudo.Defs
import Mathlib.Topology.MetricSpace.Pseudo.Pi

set_option linter.style.header false

/-!
# Statement of the affine Tverberg theorem

This file fixes a concrete Lean formulation of `theorem:main` in
`affine-tverberg17.tex`.  The paper has a polytopal case and a simplicial-ball case;
`mainTheoremStatement` is the conjunction of the two corresponding propositions.
-/

open Set

namespace AffineTverberg

/-- A finite-dimensional real coordinate space. -/
abbrev CoordinateSpace (n : ℕ) := Fin n → ℝ

section Polytope

/-- A full-dimensional convex polytope, presented as the convex hull of finitely many
points in `ℝⁿ`. -/
structure FullDimensionalPolytope (n : ℕ) where
  vertices : Finset (CoordinateSpace n)
  vertices_nonempty : vertices.Nonempty
  affineSpan_vertices : affineSpan ℝ (vertices : Set (CoordinateSpace n)) = ⊤

/-- The underlying set of a polytope. -/
def FullDimensionalPolytope.carrier {n : ℕ} (P : FullDimensionalPolytope n) :
    Set (CoordinateSpace n) :=
  convexHull ℝ (P.vertices : Set (CoordinateSpace n))

/-- A face of a polytope is an exposed subset.  For polytopes this agrees with the
usual face notion and includes the empty face and the polytope itself. -/
def FullDimensionalPolytope.IsFace {n : ℕ} (P : FullDimensionalPolytope n)
    (F : Set (CoordinateSpace n)) : Prop :=
  IsExposed ℝ P.carrier F

/-- A boundary face is a proper face. -/
def FullDimensionalPolytope.IsBoundaryFace {n : ℕ} (P : FullDimensionalPolytope n)
    (F : Set (CoordinateSpace n)) : Prop :=
  P.IsFace F ∧ F ≠ P.carrier

/-- Points of an ambient set which lie in `F`. -/
def setWithin {α : Type*} (S F : Set α) : Set S :=
  Subtype.val ⁻¹' F

/-- A map on a polytope is affine if it is the restriction of an ambient affine map. -/
def FullDimensionalPolytope.IsAffineMapOn {n d : ℕ} (P : FullDimensionalPolytope n)
    (φ : P.carrier → CoordinateSpace d) : Prop :=
  ∃ ψ : CoordinateSpace n →ᵃ[ℝ] CoordinateSpace d, ∀ x, φ x = ψ x.1

/-- The polytopal half of `theorem:main`, with `r = m + 1` and
`N = (d + 1) * m`. -/
def polytopalMainTheoremStatement : Prop :=
  ∀ (d m : ℕ), 1 ≤ d → 1 ≤ m →
    ∀ (P : FullDimensionalPolytope ((d + 1) * m))
      (φ : P.carrier → CoordinateSpace d),
      Continuous φ → P.IsAffineMapOn φ →
      ∃ F : Fin (m + 1) → Set (CoordinateSpace ((d + 1) * m)),
        (∀ i, P.IsBoundaryFace (F i)) ∧
        Pairwise (fun i j ↦ Disjoint (F i) (F j)) ∧
        ∃ y, ∀ i, y ∈ φ '' setWithin P.carrier (F i)

end Polytope

section SimplicialBall

/-- The points in the geometric realization of `K` which belong to the simplex `s`. -/
def simplicialFaceCarrier {e : ℕ}
    (K : Geometry.SimplicialComplex ℝ (CoordinateSpace e))
    (s : Finset (CoordinateSpace e)) : Set K.space :=
  Subtype.val ⁻¹' convexHull ℝ (s : Set (CoordinateSpace e))

/-- `K` is a finite pure `n`-dimensional geometric simplicial complex whose realization
is homeomorphic to the closed `n`-ball. -/
structure IsSimplicialBall {e : ℕ} (n : ℕ)
    (K : Geometry.SimplicialComplex ℝ (CoordinateSpace e)) : Prop where
  finite_faces : K.faces.Finite
  pure : ∀ s ∈ K.facets, s.card = n + 1
  homeomorph_closedBall :
    Nonempty (K.space ≃ₜ Metric.closedBall (0 : CoordinateSpace n) 1)

/-- A codimension-one simplex of a pure `n`-complex is a boundary ridge when it lies
in exactly one facet. -/
def IsBoundaryRidge {e : ℕ} (n : ℕ)
    (K : Geometry.SimplicialComplex ℝ (CoordinateSpace e))
    (s : Finset (CoordinateSpace e)) : Prop :=
  s ∈ K.faces ∧ s.card = n ∧
    ∃! facet, facet ∈ K.facets ∧ s ⊆ facet

/-- The combinatorial boundary of a simplicial ball is generated by its boundary
ridges. -/
def IsBoundarySimplicialFace {e : ℕ} (n : ℕ)
    (K : Geometry.SimplicialComplex ℝ (CoordinateSpace e))
    (s : Finset (CoordinateSpace e)) : Prop :=
  s ∈ K.faces ∧ ∃ ridge, IsBoundaryRidge n K ridge ∧ s ⊆ ridge

/-- A map on a geometric simplicial complex is affine on every simplex. -/
def IsAffineOnSimplicialFaces {e d : ℕ}
    (K : Geometry.SimplicialComplex ℝ (CoordinateSpace e))
    (φ : K.space → CoordinateSpace d) : Prop :=
  ∀ s ∈ K.faces, ∃ ψ : CoordinateSpace e →ᵃ[ℝ] CoordinateSpace d,
    ∀ x : K.space, x.1 ∈ convexHull ℝ (s : Set (CoordinateSpace e)) → φ x = ψ x.1

/-- The simplicial-ball half of `theorem:main` in the range proved in this paper:
`r = m + 1 ≥ 3` and `N = (d + 1) * m`.  The separately cited `r = 2` case is omitted. -/
def simplicialBallMainTheoremStatement : Prop :=
  ∀ (d m e : ℕ), 1 ≤ d → 2 ≤ m →
    ∀ (K : Geometry.SimplicialComplex ℝ (CoordinateSpace e)),
      IsSimplicialBall ((d + 1) * m) K →
      ∀ (φ : K.space → CoordinateSpace d),
        Continuous φ → IsAffineOnSimplicialFaces K φ →
        ∃ F : Fin (m + 1) → Finset (CoordinateSpace e),
          (∀ i, IsBoundarySimplicialFace ((d + 1) * m) K (F i)) ∧
          Pairwise (fun i j ↦ Disjoint (F i) (F j)) ∧
          ∃ y, ∀ i, y ∈ φ '' simplicialFaceCarrier K (F i)

end SimplicialBall

/-- The proposition labeled `theorem:main` in the paper, restricted in the simplicial-ball
case to `r ≥ 3`; the user requested that the separately known `r = 2` case not be formalized. -/
def mainTheoremStatement : Prop :=
  polytopalMainTheoremStatement ∧ simplicialBallMainTheoremStatement

end AffineTverberg
