import AffineTverberg.PolytopalBoundaryTopology
import AffineTverberg.PolytopalVertices
import Mathlib.Analysis.Normed.Module.HahnBanach

set_option linter.style.header false

/-!
# Exposed faces of finitely generated convex polytopes

This file develops the face theory of a `V`-polytope `conv S` (`S` a finite set
in a real normed space) that is needed to run an inductive construction over the
face lattice of a polytope:

* `exposedBy A l` is the set of maximizers of a linear functional `l` on `A`;
  every exposed face is of this shape.
* `exposedBy_convexHull`: the exposed face of a `V`-polytope determined by `l`
  is the convex hull of the generators maximizing `l`.  In particular a face is
  generated by the generators it contains.
* `isExposed_trans_convexHull`: **an exposed face of an exposed face of a
  polytope is an exposed face of the polytope**.  This is false for general
  convex bodies and uses finiteness of the generating set.
* `exists_proper_exposed_mem_segment`: **the pulling covering lemma**.  For a
  compact convex set `A`, a point `a ∈ A` and any `x ∈ A`, either `x = a` or `x`
  lies on a segment from `a` to a point of a *proper* exposed face of `A`.  This
  is the geometric engine of a pulling triangulation; no relative-interior API
  is required, the proof separates inside the direction space of the affine
  span.
-/

noncomputable section

open Set

namespace AffineTverberg
namespace PolytopeFace

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The exposed face of `A` on which the continuous linear functional `l` is
maximal. -/
def exposedBy (A : Set E) (l : E →L[ℝ] ℝ) : Set E :=
  {x ∈ A | ∀ y ∈ A, l y ≤ l x}

theorem mem_exposedBy {A : Set E} {l : E →L[ℝ] ℝ} {x : E} :
    x ∈ exposedBy A l ↔ x ∈ A ∧ ∀ y ∈ A, l y ≤ l x := Iff.rfl

theorem exposedBy_subset (A : Set E) (l : E →L[ℝ] ℝ) : exposedBy A l ⊆ A :=
  fun _ hx ↦ hx.1

theorem isExposed_exposedBy (A : Set E) (l : E →L[ℝ] ℝ) :
    IsExposed ℝ A (exposedBy A l) := fun _ ↦ ⟨l, rfl⟩

/-- Any nonempty exposed subset is the maximizer set of some functional. -/
theorem IsExposed.exists_exposedBy {A F : Set E} (hF : IsExposed ℝ A F)
    (hne : F.Nonempty) : ∃ l : E →L[ℝ] ℝ, F = exposedBy A l := hF hne

/-- **A face of a `V`-polytope is the hull of the generators it contains.** -/
theorem exposedBy_convexHull (s : Finset E) (l : E →L[ℝ] ℝ) :
    exposedBy (convexHull ℝ (s : Set E)) l =
      convexHull ℝ ((s.filter fun v ↦ ∀ w ∈ s, l w ≤ l v : Finset E) : Set E) := by
  classical
  set T := s.filter fun v ↦ ∀ w ∈ s, l w ≤ l v with hT
  apply Subset.antisymm
  · rintro x ⟨hxhull, hxmax⟩
    have hsmax : ∀ y ∈ s, l y ≤ l x := fun y hy ↦
      hxmax y (subset_convexHull ℝ _ (Finset.mem_coe.mpr hy))
    rw [Finset.convexHull_eq] at hxhull
    obtain ⟨w, hw0, hw1, hwx⟩ := hxhull
    have hxeq : ∑ y ∈ s, w y • y = x := by
      rw [← hwx, Finset.centerMass_eq_of_sum_1 _ _ hw1]
      rfl
    have hlx : ∑ y ∈ s, w y * l y = l x := by
      rw [← hxeq, map_sum]
      exact Finset.sum_congr rfl fun y _ ↦ by simp
    have hzero : ∀ y ∈ s, y ∉ T → w y = 0 := by
      intro y hy hyT
      have hlt : l y < l x := by
        rcases lt_or_eq_of_le (hsmax y hy) with h | h
        · exact h
        · exact absurd (Finset.mem_filter.mpr ⟨hy, fun z hz ↦ h ▸ hsmax z hz⟩) hyT
      by_contra hne
      have hpos : 0 < w y := lt_of_le_of_ne (hw0 y hy) (Ne.symm hne)
      have hsum : ∑ z ∈ s, w z * (l x - l z) = 0 := by
        have hcongr : ∀ z ∈ s, w z * (l x - l z) = w z * l x - w z * l z :=
          fun z _ ↦ by ring
        rw [Finset.sum_congr rfl hcongr, Finset.sum_sub_distrib, ← Finset.sum_mul, hw1,
          one_mul, hlx]
        ring
      have hnn : ∀ z ∈ s, 0 ≤ w z * (l x - l z) := fun z hz ↦
        mul_nonneg (hw0 z hz) (by linarith [hsmax z hz])
      have hzy := (Finset.sum_eq_zero_iff_of_nonneg hnn).mp hsum y hy
      nlinarith
    have hTsum : ∑ y ∈ T, w y = 1 := by
      rw [← hw1]
      exact Finset.sum_subset (Finset.filter_subset _ _) fun y hy hyT ↦ hzero y hy hyT
    have hTx : ∑ y ∈ T, w y • y = x := by
      rw [← hxeq]
      refine Finset.sum_subset (Finset.filter_subset _ _) ?_
      intro y hy hyT
      rw [hzero y hy hyT, zero_smul]
    have hmem := Finset.centerMass_mem_convexHull (R := ℝ) T
      (fun y hy ↦ hw0 y (Finset.filter_subset _ _ hy)) (by rw [hTsum]; norm_num)
      (fun y hy ↦ Finset.mem_coe.mpr hy)
    rw [Finset.centerMass_eq_of_sum_1 _ _ hTsum] at hmem
    rwa [hTx] at hmem
  · intro x hx
    have hxs : x ∈ convexHull ℝ (s : Set E) :=
      convexHull_mono (by exact_mod_cast Finset.filter_subset _ _) hx
    refine ⟨hxs, ?_⟩
    rcases (T : Set E).eq_empty_or_nonempty with hTe | ⟨v₀, hv₀⟩
    · rw [hTe] at hx; simp at hx
    · have hval : convexHull ℝ (T : Set E) ⊆ {z | l z = l v₀} := by
        apply convexHull_min
        · intro v hv
          have hv' := Finset.mem_filter.mp (Finset.mem_coe.mp hv)
          have hv₀' := Finset.mem_filter.mp (Finset.mem_coe.mp hv₀)
          exact le_antisymm (hv₀'.2 v hv'.1) (hv'.2 v₀ hv₀'.1)
        · intro c hc d hd t u ht hu htu
          simp only [Set.mem_ofPred_eq] at *
          rw [map_add, map_smul, map_smul, hc, hd]
          simp [smul_eq_mul, ← add_mul, htu]
      have hlx : l x = l v₀ := hval hx
      intro y hy
      have hle : convexHull ℝ (s : Set E) ⊆ {z | l z ≤ l v₀} := by
        apply convexHull_min
        · intro v hv
          exact (Finset.mem_filter.mp (Finset.mem_coe.mp hv₀)).2 v (Finset.mem_coe.mp hv)
        · exact convex_halfSpace_le l.toLinearMap.isLinear _
      rw [hlx]
      exact hle hy

/-- **Transitivity of exposedness for polytopes.**  An exposed face of an
exposed face of a finitely generated polytope is an exposed face of the
polytope. -/
theorem isExposed_trans_convexHull {s : Finset E} {F G : Set E}
    (hF : IsExposed ℝ (convexHull ℝ (s : Set E)) F) (hG : IsExposed ℝ F G) :
    IsExposed ℝ (convexHull ℝ (s : Set E)) G := by
  classical
  intro hGne
  have hFne : F.Nonempty := hGne.mono hG.subset
  obtain ⟨lF, hlF⟩ := hF hFne
  obtain ⟨lG, hlG⟩ := hG hGne
  set T := s.filter fun v ↦ ∀ w ∈ s, lF w ≤ lF v with hTdef
  have hFT : F = convexHull ℝ (T : Set E) := by
    rw [hlF]; exact exposedBy_convexHull s lF
  set T' := T.filter fun v ↦ ∀ w ∈ T, lG w ≤ lG v with hT'def
  have hGT' : G = convexHull ℝ (T' : Set E) := by
    rw [hlG, hFT]; exact exposedBy_convexHull T lG
  have hT'ne : T'.Nonempty := by
    rcases T'.eq_empty_or_nonempty with h | h
    · rw [hGT', h] at hGne; simp at hGne
    · exact h
  obtain ⟨v₀, hv₀⟩ := hT'ne
  have hv₀T : v₀ ∈ T := Finset.filter_subset _ _ hv₀
  have hsne : s.Nonempty := ⟨v₀, Finset.filter_subset _ _ hv₀T⟩
  set c := lF v₀ with hc
  have hTc : ∀ v ∈ T, lF v = c := by
    intro v hv
    have h1 := (Finset.mem_filter.mp hv).2 v₀ (Finset.filter_subset _ _ hv₀T)
    have h2 := (Finset.mem_filter.mp hv₀T).2 v (Finset.filter_subset _ _ hv)
    exact le_antisymm h2 h1
  obtain ⟨δ, hδpos, hδ⟩ : ∃ δ > 0, ∀ u ∈ s, u ∉ T → δ ≤ c - lF u := by
    by_cases hD : (s.filter fun u ↦ u ∉ T).Nonempty
    · obtain ⟨u₀, hu₀, hmax⟩ := Finset.exists_max_image (s.filter fun u ↦ u ∉ T) lF hD
      obtain ⟨hu₀s, hu₀T⟩ := Finset.mem_filter.mp hu₀
      have hlt : lF u₀ < c := by
        rcases lt_or_eq_of_le ((Finset.mem_filter.mp hv₀T).2 u₀ hu₀s) with h | h
        · exact h
        · exact absurd (Finset.mem_filter.mpr ⟨hu₀s, fun w hw ↦ by
            rw [h]; exact (Finset.mem_filter.mp hv₀T).2 w hw⟩) hu₀T
      exact ⟨c - lF u₀, by linarith, fun u hu huT ↦ by
        have := hmax u (Finset.mem_filter.mpr ⟨hu, huT⟩)
        linarith⟩
    · exact ⟨1, one_pos, fun u hu huT ↦
        absurd (Finset.mem_filter.mpr ⟨hu, huT⟩) fun h ↦ hD ⟨u, h⟩⟩
  obtain ⟨p, hp, hpmax⟩ := Finset.exists_max_image s (fun x ↦ |lG x|) hsne
  set B := 2 * |lG p| with hB
  have hB0 : 0 ≤ B := by positivity
  have hBbound : ∀ u ∈ s, ∀ v ∈ s, -B ≤ lG v - lG u := by
    intro u hu v hv
    have h1 : |lG u| ≤ |lG p| := hpmax u hu
    have h2 : |lG v| ≤ |lG p| := hpmax v hv
    have hu' := neg_abs_le (lG u)
    have hv' := neg_abs_le (lG v)
    have hu'' := le_abs_self (lG u)
    have hv'' := le_abs_self (lG v)
    rw [hB]; linarith
  set ε := δ / (B + 1) with hε
  have hεpos : 0 < ε := by positivity
  have hεB : ε * B < δ := by
    rw [hε, div_mul_eq_mul_div, div_lt_iff₀ (by positivity)]
    nlinarith
  refine ⟨lF + ε • lG, ?_⟩
  change G = exposedBy (convexHull ℝ (s : Set E)) (lF + ε • lG)
  rw [exposedBy_convexHull, hGT']
  congr 2
  ext v
  simp only [Finset.mem_filter, add_apply, smul_apply,
    smul_eq_mul, hT'def, hTdef]
  constructor
  · rintro ⟨hvT, hvmaxG⟩
    have hvT' : v ∈ T := Finset.mem_filter.mpr hvT
    refine ⟨Finset.filter_subset _ _ hvT', fun w hw ↦ ?_⟩
    by_cases hwT : w ∈ T
    · have := hvmaxG w (Finset.mem_filter.mp hwT)
      rw [hTc v hvT', hTc w hwT]
      nlinarith
    · have h2 := hδ w hw hwT
      have h3 := hBbound w hw v (Finset.filter_subset _ _ hvT')
      rw [hTc v hvT']
      nlinarith
  · rintro ⟨hvs, hvmax⟩
    have hvT : v ∈ T := by
      by_contra hvT
      have h1 := hvmax v₀ (Finset.filter_subset _ _ hv₀T)
      have h2 := hδ v hvs hvT
      have h3 := hBbound v hvs v₀ (Finset.filter_subset _ _ hv₀T)
      rw [hTc v₀ hv₀T] at h1
      nlinarith
    refine ⟨Finset.mem_filter.mp hvT, fun w hw ↦ ?_⟩
    have h1 := hvmax w hw.1
    rw [hTc v hvT, hTc w (Finset.mem_filter.mpr hw)] at h1
    nlinarith

section Pulling

variable [FiniteDimensional ℝ E]

/-- **Relative boundary points lie on proper exposed faces.**  If the ray from
`a` through `y` leaves the compact convex set `A` immediately after `y`, then
`y` lies on a proper exposed face of `A`. -/
theorem exists_proper_exposedBy_of_ray_exit {A : Set E} (hcl : IsClosed A)
    (hconv : Convex ℝ A) {a y : E} (ha : a ∈ A) (hy : y ∈ A) (hne : y ≠ a)
    (hexit : ∀ s : ℝ, 0 < s → y + s • (y - a) ∉ A) :
    ∃ l : E →L[ℝ] ℝ, y ∈ exposedBy A l ∧ exposedBy A l ≠ A := by
  classical
  set W := Submodule.span ℝ ((fun x ↦ x - a) '' A) with hWdef
  have hmemW : ∀ x ∈ A, x - a ∈ W := fun x hx ↦ Submodule.subset_span ⟨x, hx, rfl⟩
  set B : Set W := {w | a + (w : E) ∈ A} with hBdef
  have hmemB : ∀ w : W, w ∈ B ↔ a + (w : E) ∈ A := fun w ↦ Iff.rfl
  have hB0 : (0 : W) ∈ B := by rw [hmemB]; simpa using ha
  have hBconv : Convex ℝ B := by
    intro u hu v hv s t hs ht hst
    rw [hmemB]
    have hcast : (((s • u + t • v : W)) : E) = s • (u : E) + t • (v : E) := by push_cast; rfl
    rw [hcast, show a + (s • (u : E) + t • (v : E))
        = s • (a + (u : E)) + t • (a + (v : E)) by
      rw [smul_add, smul_add,
        show s • a + s • (u : E) + (t • a + t • (v : E))
          = (s • a + t • a) + (s • (u : E) + t • (v : E)) by abel, ← add_smul, hst, one_smul]]
    exact hconv hu hv hs ht hst
  have hBclosed : IsClosed B := hcl.preimage (by fun_prop)
  have himg : (W.subtype '' B) = (fun x ↦ x - a) '' A := by
    ext z
    constructor
    · rintro ⟨w, hw, rfl⟩
      exact ⟨a + (w : E), hw, by simp⟩
    · rintro ⟨x, hx, rfl⟩
      refine ⟨⟨x - a, hmemW x hx⟩, ?_, rfl⟩
      rw [hmemB]
      have hax : a + ((⟨x - a, hmemW x hx⟩ : W) : E) = x := by
        change a + (x - a) = x
        abel
      rw [hax]; exact hx
  have hBspan : Submodule.span ℝ B = ⊤ := by
    apply Submodule.map_injective_of_injective W.subtype_injective
    rw [Submodule.map_span, himg, Submodule.map_subtype_top]
  have hBaff : affineSpan ℝ B = ⊤ := by
    rw [eq_top_iff]
    rintro x -
    have h2 : (affineSpan ℝ B).direction = ⊤ := by
      rw [direction_affineSpan, vectorSpan_eq_span_vsub_set_right ℝ hB0,
        show (fun z ↦ z -ᵥ (0 : W)) '' B = B by ext z; simp, hBspan]
    have hbase : (0 : W) ∈ affineSpan ℝ B := subset_affineSpan ℝ B hB0
    simpa using AffineSubspace.vadd_mem_of_mem_direction
      (h2 ▸ Submodule.mem_top (x := x)) hbase
  have hBint : (interior B).Nonempty :=
    hBconv.interior_nonempty_iff_affineSpan_eq_top.mpr hBaff
  set w0 : W := ⟨y - a, hmemW y hy⟩ with hw0def
  have hw0val : ((w0 : W) : E) = y - a := rfl
  have hw0B : w0 ∈ B := by
    rw [hmemB, hw0val, show a + (y - a) = y by abel]
    exact hy
  have hw0ne : w0 ≠ 0 := by
    intro h
    apply hne
    have h1 : (y - a) = 0 := congrArg Subtype.val h
    linear_combination (norm := module) h1
  have hw0front : w0 ∈ frontier B := by
    refine ⟨subset_closure hw0B, ?_⟩
    intro hint
    obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.mp isOpen_interior w0 hint
    have hnorm : 0 < ‖w0‖ := norm_pos_iff.mpr hw0ne
    obtain ⟨t, htpos, htlt⟩ : ∃ t : ℝ, 0 < t ∧ t * ‖w0‖ < ε := by
      refine ⟨ε / (2 * ‖w0‖), by positivity, ?_⟩
      rw [div_mul_eq_mul_div, div_lt_iff₀ (by positivity)]
      nlinarith
    have hmem : w0 + t • w0 ∈ B := by
      apply interior_subset
      apply hball
      rw [Metric.mem_ball, dist_eq_norm, show w0 + t • w0 - w0 = t • w0 by abel,
        norm_smul, Real.norm_eq_abs, abs_of_pos htpos]
      exact htlt
    rw [hmemB] at hmem
    apply hexit t htpos
    have hcast : ((w0 + t • w0 : W) : E) = (y - a) + t • (y - a) := by push_cast; rfl
    rw [hcast, show a + ((y - a) + t • (y - a)) = y + t • (y - a) by abel] at hmem
    exact hmem
  obtain ⟨FW, hFWexp, hFWne, hw0FW⟩ :=
    AffineTverberg.frontier_mem_proper_exposed hBclosed hBconv hBint hw0front
  obtain ⟨lW, hlW⟩ := hFWexp ⟨w0, hw0FW⟩
  obtain ⟨L, hL, -⟩ := exists_extension_norm_eq W lW
  refine ⟨L, ⟨hy, ?_⟩, ?_⟩
  · intro z hz
    have hzW : z - a ∈ W := hmemW z hz
    have hzB : (⟨z - a, hzW⟩ : W) ∈ B := by
      rw [hmemB, show a + ((⟨z - a, hzW⟩ : W) : E) = z from by change a + (z - a) = z; abel]
      exact hz
    have hle : lW ⟨z - a, hzW⟩ ≤ lW w0 := by
      rw [hlW] at hw0FW
      exact hw0FW.2 _ hzB
    have e1 : L z - L a = lW ⟨z - a, hzW⟩ := by
      rw [← map_sub, ← hL ⟨z - a, hzW⟩]
    have e2 : L y - L a = lW w0 := by
      rw [← map_sub, ← hL w0]
    linarith
  · intro heq
    obtain ⟨u, huB, huFW⟩ : ∃ u ∈ B, u ∉ FW := by
      by_contra hcon
      rw [not_exists] at hcon
      refine hFWne (Subset.antisymm (by rw [hlW]; exact fun x hx ↦ hx.1) ?_)
      intro x hx
      by_contra hxF
      exact (hcon x) ⟨hx, hxF⟩
    rw [hlW] at huFW
    simp only [Set.mem_ofPred_eq, not_and, not_forall] at huFW
    obtain ⟨v, hvB, hlt⟩ := huFW huB
    have hlt' : lW u < lW v := not_le.mp hlt
    have hmemA : a + (u : E) ∈ A := huB
    have hmemA' : a + (v : E) ∈ A := hvB
    have hcontra : L (a + (u : E)) < L (a + (v : E)) := by
      rw [map_add, map_add, hL u, hL v]
      linarith
    have hmem : a + (u : E) ∈ exposedBy A L := by rw [heq]; exact hmemA
    exact absurd (hmem.2 _ hmemA') (not_le.mpr hcontra)

/-- **The pulling covering lemma.**  Every point of a compact convex set `A`
either equals the chosen apex `a ∈ A` or lies on a segment joining `a` to a
point of a proper exposed face of `A`. -/
theorem exists_proper_exposedBy_mem_segment {A : Set E} (hcp : IsCompact A)
    (hconv : Convex ℝ A) {a x : E} (ha : a ∈ A) (hx : x ∈ A) :
    x = a ∨ ∃ (l : E →L[ℝ] ℝ) (y : E),
      y ∈ exposedBy A l ∧ exposedBy A l ≠ A ∧ x ∈ segment ℝ a y := by
  by_cases hxa : x = a
  · exact Or.inl hxa
  right
  have hxane : x - a ≠ 0 := sub_ne_zero_of_ne hxa
  have hnorm : 0 < ‖x - a‖ := norm_pos_iff.mpr hxane
  set T : Set ℝ := {t | 0 ≤ t ∧ a + t • (x - a) ∈ A} with hTdef
  have hcont : Continuous fun t : ℝ ↦ a + t • (x - a) := by fun_prop
  have hTclosed : IsClosed T := by
    have hTeq : T = {t : ℝ | 0 ≤ t} ∩ (fun t : ℝ ↦ a + t • (x - a)) ⁻¹' A := by
      ext t; simp [hTdef, and_comm]
    rw [hTeq]
    exact (isClosed_le continuous_const continuous_id).inter (hcp.isClosed.preimage hcont)
  have hTne : T.Nonempty := ⟨1, zero_le_one, by simpa using hx⟩
  have hTbdd : BddAbove T := by
    obtain ⟨R, hR⟩ := hcp.isBounded.subset_closedBall 0
    refine ⟨(R + ‖a‖) / ‖x - a‖, ?_⟩
    rintro t ⟨ht0, htA⟩
    have h1 : ‖a + t • (x - a)‖ ≤ R := by simpa using hR htA
    have h2 : t * ‖x - a‖ ≤ ‖a + t • (x - a)‖ + ‖a‖ := by
      have h := norm_sub_le (a + t • (x - a)) a
      simp only [add_sub_cancel_left, norm_smul, Real.norm_eq_abs, abs_of_nonneg ht0] at h
      linarith
    rw [le_div_iff₀ hnorm]
    linarith
  have hsup : sSup T ∈ T := hTclosed.csSup_mem hTne hTbdd
  set t := sSup T with htdef
  have h1t : 1 ≤ t := le_csSup hTbdd ⟨zero_le_one, by simpa using hx⟩
  set y := a + t • (x - a) with hy
  have hyA : y ∈ A := hsup.2
  have hyne : y ≠ a := by
    intro h
    have hzero : t • (x - a) = 0 := by
      rw [hy] at h
      linear_combination (norm := module) h
    rcases smul_eq_zero.mp hzero with h' | h'
    · linarith
    · exact hxane h'
  have hexit : ∀ s : ℝ, 0 < s → y + s • (y - a) ∉ A := by
    intro s hs hmem
    have hgt : t < t * (1 + s) := by nlinarith
    have hmemT : t * (1 + s) ∈ T := by
      refine ⟨by nlinarith, ?_⟩
      have heq : a + (t * (1 + s)) • (x - a) = y + s • (y - a) := by
        rw [hy]; module
      rw [heq]; exact hmem
    exact absurd (le_csSup hTbdd hmemT) (not_le.mpr hgt)
  obtain ⟨l, hyl, hproper⟩ :=
    exists_proper_exposedBy_of_ray_exit hcp.isClosed hconv ha hyA hyne hexit
  refine ⟨l, y, hyl, hproper, ?_⟩
  have ht0 : t ≠ 0 := by linarith
  refine ⟨1 - 1 / t, 1 / t, ?_, by positivity, by ring, ?_⟩
  · have hle : 1 / t ≤ 1 := by
      rw [div_le_one (by linarith)]; linarith
    linarith
  · rw [hy, smul_add, smul_smul, one_div, inv_mul_cancel₀ ht0, one_smul]
    module

end Pulling

end PolytopeFace
end AffineTverberg
